<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-10T11:05:44 PST" name="Default suite" finished-at="2023-02-10T11:06:08 PST" duration-ms="24618">
    <groups>
    </groups>
    <test started-at="2023-02-10T11:05:44 PST" name="Default test" finished-at="2023-02-10T11:06:08 PST" duration-ms="24618">
      <class name="com.jan23.tests.TekarchAutomation">
        <test-method is-config="true" signature="setUpBeforeTest()[pri:0, instance:com.jan23.tests.TekarchAutomation@6e171cd7]" started-at="2023-02-10T11:05:45 PST" name="setUpBeforeTest" finished-at="2023-02-10T11:05:47 PST" duration-ms="2067" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeTest -->
        <test-method is-config="true" signature="setUpBeforeTestMethod(java.lang.String,java.lang.reflect.Method)[pri:0, instance:com.jan23.tests.TekarchAutomation@6e171cd7]" started-at="2023-02-10T11:05:47 PST" name="setUpBeforeTestMethod" finished-at="2023-02-10T11:05:57 PST" duration-ms="9721" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void com.jan23.tests.TekarchAutomation.Student_registration_Form() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeTestMethod -->
        <test-method signature="Student_registration_Form()[pri:0, instance:com.jan23.tests.TekarchAutomation@6e171cd7]" started-at="2023-02-10T11:05:57 PST" name="Student_registration_Form" finished-at="2023-02-10T11:06:07 PST" duration-ms="10421" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at com.jan23.tests.TekarchAutomation.Student_registration_Form(TekarchAutomation.java:130)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Student_registration_Form -->
        <test-method is-config="true" signature="teardownAfterTestMethod()[pri:0, instance:com.jan23.tests.TekarchAutomation@6e171cd7]" started-at="2023-02-10T11:06:08 PST" name="teardownAfterTestMethod" finished-at="2023-02-10T11:06:08 PST" duration-ms="823" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardownAfterTestMethod -->
      </class> <!-- com.jan23.tests.TekarchAutomation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
